config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Rushing Players', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      	<%= link_to 'About', home_about_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Project</h1>
<br/>
<h2>Challenge Background:</h2>
We have sets of records representing football players' rushing statistics. All records have the following attributes:
<ul>
	<li>Player (Player's name)</li>
	<li>Team (Player's team abbreviation)</li>
	<li>Pos (Player's postion)</li>
	<li>Att/G (Rushing Attempts Per Game Average)</li>
	<li>Att (Rushing Attempts)</li>
	<li>Yds (Total Rushing Yards)</li>
	<li>Avg (Rushing Average Yards Per Attempt)</li>
	<li>Yds/G (Rushing Yards Per Game)</li>
	<li>TD (Total Rushing Touchdowns)</li>
	<li>Lng (Longest Rush -- a T represents a touchdown occurred)</li>
	<li>1st (Rushing First Downs)</li>
	<li>1st% (Rushing First Down Percentage)</li>
	<li>20+ (Rushing 20+ Yards Each)</li>
	<li>40+ (Rushing 40+ Yards Each)</li>
	<li>FUM (Rushing Fumbles)</li>
</ul>

<h2>Given:</h2>
A sample data file rushing.json.
<br/><br/>
<h2>Challenge Requirements:</h2>
Create a web app (The system should be able to potentially support larger sets of data on the order of 10k records)
<ul>
	<li>Create a webpage which displays a table with the contents of rushing.json</li>
	<li>The user should be able to sort the players by Total Rushing Yards, Longest Rush and Total Rushing Touchdowns</li>
	<li>The user should be able to filter by the player's name</li>
	<li>The user should be able to download the sorted data as a CSV, as well as a filtered subset</li>
</ul>
<h2>Installation and running this solution</h2>
This problem has been solved using Javascript and Ruby on Rails framework
<ul>
	<li>Ruby 2.7.2</li>
	<li>Rails 6.0.3.4</li>
</ul>
To run this project one should have Ruby on Rails setup in his/her machine. The file <strong>rushing.json</strong> is located in /public folder of the project. One can replace this json file. If the json file is replaced with different name, one should rename the json file mentioned in Line#3 of playersrushingdata.js file located in /app/javascript/packs
<br/><br/>
Use Git Bash or cmd to run this application:
<ul>
	<li>Go to project location using Git Bash or cmd</li>
	<li>Command "rails s" to run the server</li>
	<li>Visit "http://localhost:3000/" in your browser</li>
	<li>Use "search box" for filtering, respective "Up" or "Down" arrows for sorting, "Download as CSV" button for downloading data</li>
</ul>

app/views/home/index.html.erb
<style>
    th{color:#fff;}
    .sortCol{cursor: pointer;}
</style>
<input id="search-input" type="text" placeholder="Search Player">
<a href="#" class="btn btn-secondary btn-sm" onclick="download_table_as_csv('plyer_records');">Download as CSV</a>
<br/><br/>
<table id="plyer_records" class="table table-striped table-bordered table-hover">
    <tr class="thead-dark">
        <th>Player</th>
        <th>Team</th>
        <th>Pos</th>
		<th>Att</th>
		<th>Att/G</th>
		<th class="sortCol" data-colname="Yds" data-order="desc">Yds &#9650</th>
		<th>Avg</th>
		<th>Yds/G</th>
		<th class="sortCol" data-colname="TD" data-order="desc">TD &#9650</th>
		<th class="sortCol" data-colname="Lng" data-order="desc">Lng &#9650</th>
		<th>1st</th>
		<th>1st%</th>
		<th>20+</th>
		<th>40+</th>
		<th>FUM</th>
    </tr>
    <tbody id="myTable"></tbody>
</table>
<%= javascript_pack_tag 'playersrushingdata' %>
<script>
// export target #table_id into a csv
function download_table_as_csv(table_id) {
  // Select rows from table_id
  var rows = document.querySelectorAll('table#' + table_id + ' tr');
  // Construct csv
  var csv = [];
  for (var i = 0; i < rows.length; i++) {
    var row = [], cols = rows[i].querySelectorAll('td, th');
    for (var j = 0; j < cols.length; j++) {
      // Clean innertext to remove multiple spaces and jumpline (break csv)
      var data = cols[j].innerText.replace(/(\r\n|\n|\r|▲|▼)/gm, '').replace(/(\s\s)/gm, ' ')
      // Escape double-quote with double-double-quote (source: https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv)
      data = data.replace(/"/g, '""');
      // Push escaped string
      row.push('"' + data + '"');
    }
    csv.push(row.join(','));
  }
  var csv_string = csv.join('\n');
  // Download it
  var filename = 'export_' + table_id + '_' + new Date().toLocaleDateString() + '.csv';
  var link = document.createElement('a');
  link.style.display = 'none';
  link.setAttribute('target', '_blank');
  link.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv_string));
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
</script>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Rushing Players</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  </head>
  <body>
    <%= render 'home/header' %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>